name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn run build
      - run: gulp build:plugin
      - name: WordPress Plugin Deploy
        uses: vunamhung/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
